# Generated by Django 5.2.6 on 2025-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('facebook', models.URLField(help_text='URL FaceBook', verbose_name='FaceBook')),
                ('twitter', models.URLField(help_text='URL Twitter', verbose_name='Twitter')),
                ('github', models.URLField(help_text='URL GitHub', verbose_name='GitHub')),
                ('google', models.URLField(help_text='URL Google', verbose_name='Google')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
