# Generated by Django 5.2.6 on 2025-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0004_teammember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Imgaes',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='imgaes',
            options={'verbose_name': 'Галлерия', 'verbose_name_plural': 'Галлерий'},
        ),
    ]
