# Generated by Django 5.2.6 on 2025-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0005_rename_images_imgaes_delete_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='imgaes',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
    ]
